#!/usr/bin/env python3
"""
Setup script to create frontend .env file with proper API configuration
"""
import os
import sys

def create_env_file():
    """Create .env file in frontend directory"""
    
    frontend_dir = os.path.join(os.path.dirname(__file__), 'frontend')
    env_file = os.path.join(frontend_dir, '.env')
    env_example = os.path.join(frontend_dir, '.env.example')
    
    # Check if .env already exists
    if os.path.exists(env_file):
        response = input(f".env file already exists at {env_file}. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("Keeping existing .env file.")
            return
    
    print("\n=== Frontend Environment Configuration ===\n")
    print("This script will create a .env file for your frontend configuration.")
    print(f"Location: {env_file}\n")
    
    # Get API URL from user
    default_api_url = "http://localhost:5000/api"
    print(f"Default API URL: {default_api_url}")
    api_url = input("Enter API Base URL (press Enter for default): ").strip()
    
    if not api_url:
        api_url = default_api_url
    
    # Create .env content
    env_content = f"""# API Configuration
# Generated by setup-frontend-env.py

VITE_API_BASE_URL={api_url}

# For production, update this to your deployed backend URL
# Example: VITE_API_BASE_URL=https://your-backend-domain.com/api
"""
    
    # Write .env file
    try:
        with open(env_file, 'w') as f:
            f.write(env_content)
        print(f"\n✅ Successfully created .env file at: {env_file}")
        print(f"   API Base URL: {api_url}")
        print("\nNext steps:")
        print("1. Start backend server: cd backend && python api.py")
        print("2. Start frontend server: cd frontend && npm run dev")
        print("3. Open browser to http://localhost:8080")
    except Exception as e:
        print(f"\n❌ Error creating .env file: {e}")
        sys.exit(1)

def main():
    """Main entry point"""
    print("=" * 60)
    print("Traffic Analytics Dashboard - Frontend Setup")
    print("=" * 60)
    
    create_env_file()
    
    print("\n" + "=" * 60)
    print("Setup complete! See CONFIGURATION.md for more details.")
    print("=" * 60)

if __name__ == '__main__':
    main()

